// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaTmRVGWIX5vMkhveglLQeXis0kOZQVuc',
    appId: '1:197017228975:web:922b4c497e127fe8e8a65a',
    messagingSenderId: '197017228975',
    projectId: 'aquation-5c8a8',
    authDomain: 'aquation-5c8a8.firebaseapp.com',
    storageBucket: 'aquation-5c8a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZnqhx0Ikih0aD8IhKDlz_MD42U5_9048',
    appId: '1:197017228975:android:5408ef146ab8fabee8a65a',
    messagingSenderId: '197017228975',
    projectId: 'aquation-5c8a8',
    storageBucket: 'aquation-5c8a8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaTmRVGWIX5vMkhveglLQeXis0kOZQVuc',
    appId: '1:197017228975:web:2f537890b6a4d225e8a65a',
    messagingSenderId: '197017228975',
    projectId: 'aquation-5c8a8',
    authDomain: 'aquation-5c8a8.firebaseapp.com',
    storageBucket: 'aquation-5c8a8.firebasestorage.app',
  );
}
